// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReviewWord struct {
	WrongAnswers int32
	WordID       int64
	UserID       int64
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Stage struct {
	ID          int64
	Level       int32
	HoursToNext int32
	CreatedAt   pgtype.Timestamptz
}

type Translation struct {
	ID          int64
	Translation string
	WordID      int64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash []byte
	CreatedAt    pgtype.Timestamptz
}

type Word struct {
	ID         int64
	Word       string
	NextReview pgtype.Timestamptz
	StageID    int64
	UserID     int64
}
