// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: words.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTranslation = `-- name: AddTranslation :exec
INSERT INTO translations (translation, word_id)
VALUES ($1, $2)
`

type AddTranslationParams struct {
	Translation string
	WordID      int64
}

func (q *Queries) AddTranslation(ctx context.Context, arg AddTranslationParams) error {
	_, err := q.db.Exec(ctx, addTranslation, arg.Translation, arg.WordID)
	return err
}

const addWord = `-- name: AddWord :exec
INSERT INTO words (word, next_review, stage_id, user_id)
VALUES ($1, $2, $3, $4)
`

type AddWordParams struct {
	Word       string
	NextReview pgtype.Timestamptz
	StageID    int64
	UserID     int64
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) error {
	_, err := q.db.Exec(ctx, addWord,
		arg.Word,
		arg.NextReview,
		arg.StageID,
		arg.UserID,
	)
	return err
}

const getStageByLevel = `-- name: GetStageByLevel :one
SELECT id, level, hours_to_next FROM stages WHERE level = $1
`

type GetStageByLevelRow struct {
	ID          int64
	Level       int32
	HoursToNext int32
}

func (q *Queries) GetStageByLevel(ctx context.Context, level int32) (GetStageByLevelRow, error) {
	row := q.db.QueryRow(ctx, getStageByLevel, level)
	var i GetStageByLevelRow
	err := row.Scan(&i.ID, &i.Level, &i.HoursToNext)
	return i, err
}
